<?php
declare(strict_types=1);

// Lob SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

LobUtility::setRegistrar(function (LobUtility $u): void {
    $u->clean = [LobClean::class, 'call'];
    $u->done = [LobDone::class, 'call'];
    $u->make_error = [LobMakeError::class, 'call'];
    $u->feature_add = [LobFeatureAdd::class, 'call'];
    $u->feature_hook = [LobFeatureHook::class, 'call'];
    $u->feature_init = [LobFeatureInit::class, 'call'];
    $u->fetcher = [LobFetcher::class, 'call'];
    $u->make_fetch_def = [LobMakeFetchDef::class, 'call'];
    $u->make_context = [LobMakeContext::class, 'call'];
    $u->make_options = [LobMakeOptions::class, 'call'];
    $u->make_request = [LobMakeRequest::class, 'call'];
    $u->make_response = [LobMakeResponse::class, 'call'];
    $u->make_result = [LobMakeResult::class, 'call'];
    $u->make_point = [LobMakePoint::class, 'call'];
    $u->make_spec = [LobMakeSpec::class, 'call'];
    $u->make_url = [LobMakeUrl::class, 'call'];
    $u->param = [LobParam::class, 'call'];
    $u->prepare_auth = [LobPrepareAuth::class, 'call'];
    $u->prepare_body = [LobPrepareBody::class, 'call'];
    $u->prepare_headers = [LobPrepareHeaders::class, 'call'];
    $u->prepare_method = [LobPrepareMethod::class, 'call'];
    $u->prepare_params = [LobPrepareParams::class, 'call'];
    $u->prepare_path = [LobPreparePath::class, 'call'];
    $u->prepare_query = [LobPrepareQuery::class, 'call'];
    $u->graphql_body = [LobGraphql::class, 'body'];
    $u->graphql_errors = [LobGraphql::class, 'errors'];
    $u->result_basic = [LobResultBasic::class, 'call'];
    $u->result_body = [LobResultBody::class, 'call'];
    $u->result_headers = [LobResultHeaders::class, 'call'];
    $u->transform_request = [LobTransformRequest::class, 'call'];
    $u->transform_response = [LobTransformResponse::class, 'call'];
});
